default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: todo_app_development

test:
  <<: *default
  database: todo_app_test

production:
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: todo_app_productioin
  username: root
  password:
  host: mysql://b3f9c7b14062b6:03d84cd1@us-cdbr-east-06.cleardb.net/heroku_92148b4b0649e52?reconnect=true